# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from pic2str import explode2, explode
import base64
from io import BytesIO
from PIL import Image, ImageQt

# Load byte data
byte_data = base64.b64decode(explode)
image_data = BytesIO(byte_data)
image = Image.open(image_data)

# PIL to QPixmap
qImage = ImageQt.ImageQt(image)

byte_data2 = base64.b64decode(explode2)
image_data2 = BytesIO(byte_data2)
image2 = Image.open(image_data2)

# PIL to QPixmap
qImage2 = ImageQt.ImageQt(image2)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1389, 914)
        icon = QtGui.QIcon()
        icon2 = QtGui.QPixmap.fromImage(qImage2)
        icon.addPixmap(icon2, QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(350, 20, 991, 701))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 60, 274, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_choosefile = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_choosefile.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_choosefile.setFont(font)
        self.pushButton_choosefile.setStyleSheet("background-color: rgb(115, 115, 115);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Sans Serif\";")
        self.pushButton_choosefile.setObjectName("pushButton_choosefile")
        self.horizontalLayout_2.addWidget(self.pushButton_choosefile)
        self.pushButton_clear = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clear.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 11pt \"MS Sans Serif\";")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout_2.addWidget(self.pushButton_clear)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.listWidget_files = QtWidgets.QListWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listWidget_files.setFont(font)
        self.listWidget_files.setDragEnabled(True)
        self.listWidget_files.setDragDropOverwriteMode(False)
        self.listWidget_files.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listWidget_files.setAlternatingRowColors(False)
        self.listWidget_files.setObjectName("listWidget_files")
        self.verticalLayout_2.addWidget(self.listWidget_files)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(500, 780, 381, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1.setFont(font)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_split = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_split.setFont(font)
        self.pushButton_split.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);\n"
"font: 75 11pt \"MS Sans Serif\";")
        self.pushButton_split.setObjectName("pushButton_split")
        self.horizontalLayout.addWidget(self.pushButton_split)
        self.pushButton_reorganize = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_reorganize.setFont(font)
        self.pushButton_reorganize.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 11pt \"MS Sans Serif\";\n"
"background-color: rgb(0, 199, 0);")
        self.pushButton_reorganize.setObjectName("pushButton_reorganize")
        self.horizontalLayout.addWidget(self.pushButton_reorganize)
        self.pushButton_merge = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_merge.setFont(font)
        self.pushButton_merge.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"font: 75 11pt \"MS Sans Serif\";")
        self.pushButton_merge.setObjectName("pushButton_merge")
        self.horizontalLayout.addWidget(self.pushButton_merge)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(40, 420, 261, 261))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.listWidget = QtWidgets.QListWidget(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listWidget.setFont(font)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(850, 880, 28, 24))
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        image = QtGui.QPixmap.fromImage(qImage)
        icon1.addPixmap(image, QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(501, 881, 341, 21))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PDF Handler"))
        self.pushButton_choosefile.setText(_translate("MainWindow", "Seleccione los archivos"))
        self.pushButton_clear.setText(_translate("MainWindow", "Limpiar"))
        self.listWidget_files.setSortingEnabled(True)
        self.label_1.setText(_translate("MainWindow", "Seleccione una operación"))
        self.pushButton_split.setText(_translate("MainWindow", "Dividir"))
        self.pushButton_reorganize.setText(_translate("MainWindow", "Reorganizar"))
        self.pushButton_merge.setText(_translate("MainWindow", "Unir"))
        self.label_2.setText(_translate("MainWindow", "Seleccione y/o reorganice las páginas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
